/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *Roll;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *Add;
  GtkWidget *Name;
  GtkWidget *Branch;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *Edit;
  GtkWidget *Delete;
  GtkWidget *Search;
  GtkWidget *Exit;
  GtkWidget *Next;
  GtkWidget *Prev;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window1), 1);
  gtk_window_set_title (GTK_WINDOW (window1), _("My Collge Addmission"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 144, 32);
  gtk_widget_set_size_request (entry1, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 144, 96);
  gtk_widget_set_size_request (entry2, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 144, 160);
  gtk_widget_set_size_request (entry3, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  Roll = gtk_label_new (_("ROLL NO."));
  gtk_widget_show (Roll);
  gtk_fixed_put (GTK_FIXED (fixed1), Roll, 50, 32);
  gtk_widget_set_size_request (Roll, 80, 40);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed1), entry4, 144, 216);
  gtk_widget_set_size_request (entry4, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed1), entry5, 144, 272);
  gtk_widget_set_size_request (entry5, 176, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  Add = gtk_button_new_with_mnemonic (_("ADD"));
  gtk_widget_show (Add);
  gtk_fixed_put (GTK_FIXED (fixed1), Add, 48, 352);
  gtk_widget_set_size_request (Add, 64, 40);

  Name = gtk_label_new (_("NAME"));
  gtk_widget_show (Name);
  gtk_fixed_put (GTK_FIXED (fixed1), Name, 56, 88);
  gtk_widget_set_size_request (Name, 56, 48);

  Branch = gtk_label_new (_("BRANCH"));
  gtk_widget_show (Branch);
  gtk_fixed_put (GTK_FIXED (fixed1), Branch, 56, 160);
  gtk_widget_set_size_request (Branch, 64, 40);

  label1 = gtk_label_new (_("E-MAIL"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 48, 216);
  gtk_widget_set_size_request (label1, 72, 48);

  label2 = gtk_label_new (_("MOB"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 48, 272);
  gtk_widget_set_size_request (label2, 64, 48);

  Edit = gtk_button_new_with_mnemonic (_("EDIT"));
  gtk_widget_show (Edit);
  gtk_fixed_put (GTK_FIXED (fixed1), Edit, 120, 352);
  gtk_widget_set_size_request (Edit, 64, 40);

  Delete = gtk_button_new_with_mnemonic (_("DEL"));
  gtk_widget_show (Delete);
  gtk_fixed_put (GTK_FIXED (fixed1), Delete, 192, 352);
  gtk_widget_set_size_request (Delete, 64, 40);

  Search = gtk_button_new_with_mnemonic (_("SEARCH"));
  gtk_widget_show (Search);
  gtk_fixed_put (GTK_FIXED (fixed1), Search, 264, 352);
  gtk_widget_set_size_request (Search, 72, 40);

  Exit = gtk_button_new_with_mnemonic (_("EXIT"));
  gtk_widget_show (Exit);
  gtk_fixed_put (GTK_FIXED (fixed1), Exit, 240, 400);
  gtk_widget_set_size_request (Exit, 80, 40);

  Next = gtk_button_new_with_mnemonic (_("NEXT"));
  gtk_widget_show (Next);
  gtk_fixed_put (GTK_FIXED (fixed1), Next, 80, 400);
  gtk_widget_set_size_request (Next, 72, 40);

  Prev = gtk_button_new_with_mnemonic (_("PREV"));
  gtk_widget_show (Prev);
  gtk_fixed_put (GTK_FIXED (fixed1), Prev, 160, 400);
  gtk_widget_set_size_request (Prev, 72, 40);

  g_signal_connect ((gpointer) Add, "clicked",
                    G_CALLBACK (on_Add_clicked),
                    NULL);
  g_signal_connect ((gpointer) Edit, "clicked",
                    G_CALLBACK (on_Edit_clicked),
                    NULL);
  g_signal_connect ((gpointer) Delete, "clicked",
                    G_CALLBACK (on_Delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) Search, "clicked",
                    G_CALLBACK (on_Search_clicked),
                    NULL);
  g_signal_connect ((gpointer) Exit, "clicked",
                    G_CALLBACK (on_Exit_clicked),
                    NULL);
  g_signal_connect ((gpointer) Next, "clicked",
                    G_CALLBACK (on_Next_clicked),
                    NULL);
  g_signal_connect ((gpointer) Prev, "clicked",
                    G_CALLBACK (on_Prev_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, Roll, "Roll");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, Add, "Add");
  GLADE_HOOKUP_OBJECT (window1, Name, "Name");
  GLADE_HOOKUP_OBJECT (window1, Branch, "Branch");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, Edit, "Edit");
  GLADE_HOOKUP_OBJECT (window1, Delete, "Delete");
  GLADE_HOOKUP_OBJECT (window1, Search, "Search");
  GLADE_HOOKUP_OBJECT (window1, Exit, "Exit");
  GLADE_HOOKUP_OBJECT (window1, Next, "Next");
  GLADE_HOOKUP_OBJECT (window1, Prev, "Prev");

  return window1;
}

